spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: authentication
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  ssl:
    key-store-type: PKCS12
    key-store: file:authentication.p12
    key-store-password: ZvqgnmkW1pb3OGdr
    key-password: ${server.ssl.key-store-password}
    key-alias: 1
    client-auth: none
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server.port: 0
